---

- name: Ensure that a logstash user is exist
  user: name=logstash system=yes groups=adm

- include: install.deb.yml
  when: ansible_os_family == 'Debian'
  tags: [logstash, logstash-install]

- include: configure-common.yml
  tags: [logstash, logstash-configure]

- include: configure-server.yml
  when: logstash_enabled
  tags: [logstash, logstash-configure]

- include: configure-forwarder.yml
  when: logstash_forwarder_enabled
  tags: [logstash, logstash-configure]
